# Generated by Django 6.0.3 on 2026-03-23 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('modeling', 'Моделирование'), ('printing', 'Печать'), ('postprocessing', 'Постобработка'), ('ready', 'Готов к выдаче'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='Файл 3D модели')),
                ('model_description', models.TextField(blank=True, help_text='Особенности печати, цвет, размеры', verbose_name='Описание модели')),
                ('estimated_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предполагаемый вес (г)')),
                ('estimated_print_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Предполагаемое время печати (часы)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма без доставки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Примечания к доставке')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ФИО получателя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('product_type', models.CharField(choices=[('material', 'Материал для печати'), ('service', 'Услуга печати'), ('accessory', 'Аксессуар')], default='material', max_length=20, verbose_name='Тип товара')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('material_type', models.CharField(blank=True, help_text='PLA, ABS, PETG, Resin и т.д.', max_length=50, verbose_name='Тип материала')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Диаметр (мм)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('g', 'Грамм'), ('pcs', 'Штука'), ('hour', 'Час')], default='g', max_length=10, verbose_name='Единица измерения')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)')),
                ('min_print_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мин. время печати (часы)')),
                ('max_print_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. время печати (часы)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('specifications', models.TextField(blank=True, help_text='Температура печати, прочность и т.д.', verbose_name='Технические характеристики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('color_choice', models.CharField(blank=True, max_length=50, verbose_name='Выбранный цвет')),
                ('infill_percent', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент заполнения')),
                ('layer_height', models.DecimalField(blank=True, decimal_places=2, default=0.2, max_digits=4, null=True, verbose_name='Высота слоя (мм)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
    ]
