# Generated by Django 6.0.3 on 2026-03-23 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_print_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Фактическое время печати (часы)'),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактический вес (г)'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tracking',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трек-номер'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='model_notes',
            field=models.TextField(blank=True, help_text='Поддержки, ориентация печати и т.д.', verbose_name='Технические примечания'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен полностью'), ('refunded', 'Возвращен')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exposure_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время экспозиции (сек)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='need_painting',
            field=models.BooleanField(default=False, verbose_name='Покраска'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='need_polishing',
            field=models.BooleanField(default=False, verbose_name='Шлифовка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='need_support',
            field=models.BooleanField(default=True, verbose_name='Требуются поддержки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='resin_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип смолы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/%Y/%m/%d/', verbose_name='Файл 3D модели'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='infill_percent',
            field=models.IntegerField(choices=[(0, '0% - Пустой'), (10, '10%'), (20, '20% - Экономичный'), (50, '50% - Стандартный'), (75, '75% - Прочный'), (100, '100% - Максимальная прочность')], default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент заполнения'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='layer_height',
            field=models.DecimalField(blank=True, choices=[(0.1, '0.10 мм - Высокое качество'), (0.15, '0.15 мм'), (0.2, '0.20 мм - Стандарт'), (0.25, '0.25 мм'), (0.3, '0.30 мм - Быстрая печать')], decimal_places=2, default=0.2, max_digits=4, null=True, verbose_name='Высота слоя (мм)'),
        ),
    ]
