# Generated by Django 6.0.3 on 2026-03-23 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_actual_print_time_order_actual_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=50, verbose_name='Тип материала')),
                ('volume', models.FloatField(verbose_name='Объем модели (см³)')),
                ('infill', models.IntegerField(default=20, verbose_name='Процент заполнения (%)')),
                ('layer_height', models.FloatField(default=0.2, verbose_name='Высота слоя (мм)')),
                ('weight', models.FloatField(verbose_name='Вес модели (г)')),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость материала')),
                ('print_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость печати')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История расчета',
                'verbose_name_plural': 'История расчетов',
                'ordering': ['-created_at'],
            },
        ),
    ]
