# Generated by Django 6.0.3 on 2026-03-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_calculationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем модели (см³)'),
        ),
        migrations.AddField(
            model_name='order',
            name='model_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расчетный вес (г)'),
        ),
        migrations.AddField(
            model_name='order',
            name='technical_notes',
            field=models.TextField(blank=True, help_text='Особенности печати: поддержки, ориентация, постобработка', verbose_name='Технические требования'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('default_address', models.TextField(blank=True, verbose_name='Адрес по умолчанию')),
                ('preferred_material', models.CharField(blank=True, max_length=50, verbose_name='Предпочитаемый материал')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления по email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
