# Generated by Django 6.0.3 on 2026-03-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_model_volume_order_model_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('material_type', models.CharField(choices=[('fdm', 'FDM пластик (нить)'), ('sla', 'SLA смола'), ('sls', 'SLS порошок')], max_length=10, verbose_name='Тип материала')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('density', models.DecimalField(decimal_places=2, default=1.24, max_digits=5, verbose_name='Плотность (г/см³)')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за грамм (руб)')),
                ('print_temperature', models.CharField(blank=True, max_length=50, verbose_name='Температура печати')),
                ('bed_temperature', models.CharField(blank=True, max_length=50, verbose_name='Температура стола')),
                ('strength', models.CharField(blank=True, max_length=100, verbose_name='Прочность')),
                ('flexibility', models.CharField(blank=True, max_length=100, verbose_name='Гибкость')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome иконка', max_length=50, verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Вид пластика',
                'verbose_name_plural': 'Виды пластиков',
                'ordering': ['material_type', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Товар/услуга', 'verbose_name_plural': 'Товары и услуги'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_print_time_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_print_time_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размеры (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. время (часы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мин. время (часы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.CharField(blank=True, help_text='например: "за штуку", "за грамм", "за час"', max_length=50, verbose_name='Единица цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (г)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='К какому типу изделий относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория изделия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ready_product', 'Готовое изделие'), ('printing_service', 'Услуга печати'), ('modeling_service', 'Услуга моделирования'), ('postprocessing_service', 'Услуга постобработки')], default='ready_product', max_length=30, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Из какого материала изготавливается (для готовых изделий и услуг)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.material', verbose_name='Вид пластика'),
        ),
    ]
