# Generated by Django 6.0.3 on 2026-03-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_material_alter_product_options_remove_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, help_text='Например: "Вид спереди", "В упаковке"', max_length=100, verbose_name='Название')),
                ('is_main', models.BooleanField(default=False, help_text='Отметьте, если это главное фото товара', verbose_name='Основное фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товаров',
                'ordering': ['order', '-is_main', 'created_at'],
            },
        ),
    ]
