# Generated by Django 6.0.3 on 2026-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_from_catalog',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы скрыть товар из общего каталога', verbose_name='Скрыть из каталога'),
        ),
    ]
