# Generated by Django 6.0.3 on 2026-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_hide_from_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размеры (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. время (часы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мин. время (часы)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (г)'),
        ),
    ]
